smb_om/smb_om/Controllers/OpsAdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using smb_om.Infrastructure;
using smb_om.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smb_om.Controllers
{
    public class OpsAdminController : Controller
    {
        readonly IOrderProcess _IOrderProcess;
        readonly IQueueSummary _IQueueSummary;
        readonly ISpecialProjectType _ISpecialProjectType;
        readonly IReasonCode _IReasonCode;
        readonly IProductReasonCode _IProductReasonCode;
        readonly ICallType _ICallType;


        public OpsAdminController(IOrderProcess IOrderProcess, IQueueSummary IqueueSummary, ISpecialProjectType IspecialProjectType, IReasonCode reasonCode, IProductReasonCode productReasonCode, ICallType ICallType)
        {
            _IOrderProcess = IOrderProcess;
            _IQueueSummary = IqueueSummary;
            _ISpecialProjectType = IspecialProjectType;
            _IReasonCode = reasonCode;
            _IProductReasonCode = productReasonCode;
            _ICallType = ICallType;
        }
        public IActionResult Index()
        {
            HttpContext.Session.Remove("Tab1CallReason");
            return View();
        }
        public IActionResult CallReason()
        {
            //var model = _ICallType.GetCalltype();
        //    var orderupdate = _ICallType.GetCalltypeReasonName(Convert.ToInt32(2));
            var model = _ICallType.GetCalltype();
          //  model.callTypeReasonNAmes = orderupdate.callTypeReasonNAmes;
            return View("CallReason", model);
          //  return View(model);
        }
        [HttpGet]
        public JsonResult CallReasonUpdate(string CallReasonID, string CallReasonName, int Isactive)
        {
            var orderupdate = _ICallType.UpdateCalltypeReasonName(Convert.ToInt32(CallReasonID), CallReasonName, Isactive);
            return Json(orderupdate);
        }
        [HttpGet]
        public JsonResult CallReasonInsert(string CallTypeID, string CallReasonName)
        {
           var v =   HttpContext.Session.GetString("UserId");

            var orderupdate = _ICallType.InsertCalltypeReasonName(Convert.ToInt32(CallTypeID), CallReasonName,1, v);
            return Json(orderupdate);
        }


        //[HttpGet]
        //public IActionResult GetCallReason(string Calltypeid)
        //{
        //    var orderupdate = _ICallType.GetCalltypeReasonName(Convert.ToInt32(Calltypeid));
        //    var model = _ICallType.GetCalltype();
        //    model.callTypeReasonNAmes = orderupdate.callTypeReasonNAmes;
        //    return View("CallReason", orderupdate);
        //}

        [HttpGet]
        public JsonResult GetCallReason(string Calltypeid)
        {
            var orderupdate = _ICallType.GetCalltypeReasonName(Convert.ToInt32(Calltypeid));
       //     var model = _ICallType.GetCalltype();
         //   model.callTypeReasonNAmes = orderupdate.callTypeReasonNAmes;
            return Json(orderupdate.callTypeReasonNAmes);
        }
        public IActionResult ReasonCode()
        {
            var result = _IReasonCode.GetReasonCode();
            return View(result);
        }

        [HttpGet]
        public JsonResult GetReasonCodeforState( string StateName)
        {
            var orderupdate = _IProductReasonCode.GetProductReasonCodeforState(StateName);
            return Json(orderupdate.reasonCodeNames);
        }
        [HttpPost]
        public IActionResult UpdateReasonCodeforState(IFormCollection keyValuePairs)
        {
            foreach (var item in keyValuePairs)
            {
                if (!item.Key.Contains("RequestVerification"))
                    _IProductReasonCode.UpdateReasonCode(Convert.ToInt32(item.Key), Convert.ToInt32( item.Value));
            }

            var model = _IProductReasonCode.GetProductReasonCode();
            return View("ProductReasonCode", model);
        }

        [HttpGet]
        public JsonResult ReasonCodeUpdate(string Rowid, string reasoncode)
        {
            var orderupdate = _IReasonCode.UpdateReasonCode(Rowid, reasoncode);
            return Json(orderupdate);
        }

        public IActionResult ProductReasonCode()
        {
            var model = _IProductReasonCode.GetProductReasonCode();
            return View(model);
        }
        public IActionResult SpecialHandleMessaging()
        {
            return View();
        }
        public IActionResult QueueSummary()
        {
             var model = _IQueueSummary.GetQueueSummary();
            return View(model);
        }
        public IActionResult UnAssign()
        {
            var lstorder = _IOrderProcess.GetNonMovableOrder();
            return View(lstorder);
        }
        [HttpGet]
        public JsonResult UnAssignOrder(string ordernumber )
        {
            var orderupdate = _IOrderProcess.UpdateUnassignOrder(ordernumber);
            return Json(orderupdate);
        }
        public IActionResult EscalationTracker()
        {
            return View();
        }
        public IActionResult SpecialProjectTracking()
        {
            var model =_ISpecialProjectType.GetPartnerAffiliate();
          //  SpecialProjectType specialProjectType = new SpecialProjectType();
            return View(model);
        }

        [HttpGet]
        public JsonResult SpecialProjectTrackingUpdate(string Rowid, string SpecialProjectType)
        {
            var orderupdate = _ISpecialProjectType.UpdateSpecialProject(Rowid, SpecialProjectType, 0, 1);
            return Json(orderupdate);
        }
        [HttpGet]
        public JsonResult SpecialProjectTrackingDelete(string Rowid, string SpecialProjectType)
        {
            var orderdelete = _ISpecialProjectType.UpdateSpecialProject(Rowid, SpecialProjectType, 1, 0);
            return Json(orderdelete);
        }
    }
}

smb_om/smb_om/Views/OpsAdmin/OpsAdmin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>

</div>

smb_om/smb_om/Views/OpsAdmin/ProductReasonCode.cshtml
@model smb_om.Model.ProductReasonCode
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<body>
    <div id="content-body">
        <form asp-controller="OpsAdmin" asp-action="UpdateReasonCodeforState" method="post" name="brvAdminForm">
            <div class="application">
                <h1>Product Reason Code</h1>
                <ul class="nav nav-tabs" style="border-right:0;border-left:0;">

                    <li class="active"><a data-toggle="tab" href="#business" aria-expanded="true">Business - SMBC</a></li>
                </ul>

                <table border="0" cellpadding="0" cellspacing="0" class="appFixedTable">
                    @*<tr class="resultsHeader">
                        <td align="center" colspan="5">Add New</td>
                    </tr>*@
                    <tr class="resultsHeader">
                        <td align="left" style="word-wrap: break-word;">
                            <select id="drpaffiliate"
                                    onchange="GetReasonCodeSate()">
                                <option value="">--Select--</option>
                                @foreach (var item in Model.stateNames)
                                {
                                <option value="@item.statename">@item.statename</option>
                                @*<option value="7TZMXNUK">7TZMXNUK</option>
        <option value="7U38D1JI">7U38D1JI</option>
        <option value="AAFES">AAFES</option>
        <option value="ABCDIND">ABCDIND</option>
        <option value="ACCELLER">ACCELLER</option>
        <option value="ACN">ACN</option>
        <option value="ADCOMM">ADCOMM</option>
        <option value="ADCOMMCH">ADCOMMCH</option>*@
                                }
                            </select>
                        </td>
                        <td align="left" style="word-wrap: break-word;">IsActive </td>
                    </tr>
                </table>
                <table border="0" cellpadding="0" cellspacing="0" class="appFixedTable" id="tblEmployee">
                    @*<tr class="resultsHeader">
                        <td align="center" colspan="5">Add New</td>
                    </tr>*@



                    @*<tr role="row" class="odd">
                        <td>test</td>
                        <td>
                            <input class="checkbox" id="quickSearchOrderOnly" name="Isordertype"
                                   type="checkbox"
                                   value="true"
                                   checked="checked" />
                        </td>
                    </tr>*@
                </table>
                <div style="display: inline-block; text-align: right; width: 100%;"><input class="button-css" type="submit" value="Submit" /></div>
            </div>
            </form>
    </div>
    <script type="text/javascript">

        function check(RowID) {

            alert(RowID);
            if ($('#' + RowID).is(":checked")) {
                // it is checked
                alert("checked");
                $('#' + RowID).val(1);
            }
            else {

                alert("unchecked");
                $('#' + RowID).val(0);
            }
          
        }

        function GetReasonCodeSate() {

            var txt = $('#drpaffiliate option:selected').text();
            if (txt == '') {

                alert('Please select valid reason code');
            }

            // var txt = $('#ordernumber').val();
            //if (txt == '') {
            //    alert('Please enter ordernumber');
            //    return;
            //}

            //     txt = ordernumber;

            //<tr role="row" class="odd">
            //    <td>test</td>
            //    <td>
            //        <input class="checkbox" id="quickSearchOrderOnly" name="Isordertype"
            //            type="checkbox"
            //            value="true"
            //            checked="checked" />
            //    </td>
            //</tr>

            $.getJSON('@Url.Content("~/")' + "OpsAdmin/GetReasonCodeforState?StateName=" + txt, function (v) {
                var data = v;
                $("#tblEmployee").empty();
                if (data != null) {

                    var tblEmployee = $("#tblEmployee");

                    $.each(data, function (index, item) {
                        console.log(item);
                        var tr = $("<tr  class=resultsOdd></tr>");
                        tr.html(("<td>" + item.reasonCode + "</td>")
                            + " " + ("<td>  <input class='checkbox' onclick=check('" + item.rowId + "')  name='" + item.rowId + "' type = 'checkbox' value = '1' checked = 'checked' /> </td>"));


                        tblEmployee.append(tr);

                    });
                }
                else {
                   // alert( "No details found");
                }


            });
                }
         @*function GetViewLog() {

            var txt = $('#ordernumber').val();
            if (txt == '') {
                alert('Please enter ordernumber');
                return;
            }

           //     txt = ordernumber;
            $.getJSON('@Url.Content("~/")' + "Admin/GetLog?ordernumber=" + txt,function (v)
            {
                var data = v;
                var ordernum = $("#spanordernumber");
                ordernum.html(data[0].ordernumber);

                if (data != null) {

                    var tblEmployee = $("#tblEmployee");
                    $.each(data, function (index, item) {
                        console.log(item.category);
                        var tr = $("<tr  class=resultsOdd></tr>");
                        tr.html(("<td>" + item.category + "</td>")
                            + " " + ("<td>" + item.date + "</td>")
                            + " " + ("<td>  <textarea class='textareaField' cols='50' rows='6' style='height: 100px;'>" + item.message +"</textarea> </td>"));


                        tblEmployee.append(tr);

                    });
                }
                    else {
                        alert("OrderNumber :" + txt + "No details found");
                    }

            });
        }*@
    </script>
</body>

smb_om/smb_om/Views/OpsAdmin/QueueSummary.cshtml
@model smb_om.Model.QueueSummary
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<body>
    <div id="content-body">
        <input name="token" type="hidden" value="89c022ca-2e78-4c7c-ba68-8a0a34e4e51e" /><input id="action" name="action" type="hidden" value="" /><input id="inputstring" name="inputstring" type="hidden" value="" /><table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td class="stroke" height="1" width="1"></td>
                <td align="center">
                    <div class="application">
                        <h1>OPS Admin</h1>
                        <p class="error"></p>
                        <div class="content-border">
                            <div class="cmxform_results">
                                <fieldset>
                                    <h2>Queue Summary</h2>
                                    <hr class="break" />
                                    <table border="0" cellpadding="0" cellspacing="0" class="appFixedTable">
                                        <tr class="resultsHeader">
                                            <td align="left" style="width: 15%;">MLP</td>
                                            <td align="left" style="width: 15%;">COUNT</td>
                                            <td align="left" style="width: 15%;">DAYS</td>
                                        </tr>
                                        <tr>
                                            <td>Business</td>
                                            <td>@Model.MLP.ordercount</td>
                                            <td>@Model.MLP.MinimumDays</td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="appFixedTable">
                                        <tr class="resultsHeader">
                                            <td align="left" style="width: 15%;">INCOMPLETE</td>
                                            <td align="left" style="width: 15%;">COUNT</td>
                                            <td align="left" style="width: 15%;">DAYS</td>
                                        </tr>
                                        @*<tr>
                                            <td>Residential</td>
                                            <td>1</td>
                                            <td>25 days 6 hours 36 minutes</td>
                                        </tr>*@
                                        <tr>
                                            <td>Business</td>
                                            <td>@Model.Incomplete.ordercount</td>
                                            <td>@Model.Incomplete.MinimumDays</td>
                                        </tr>
                                    </table>
                                    <table border="0" cellpadding="0" cellspacing="0" class="appFixedTable">
                                        <tr class="resultsHeader">
                                            <td align="left" style="width: 15%;">CHECK INSTALL</td>
                                            <td align="left" style="width: 15%;">COUNT</td>
                                            <td align="left" style="width: 15%;">DAYS</td>
                                        </tr>
                                        @*<tr>
            <td>Residential</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td align="center">Check Install I</td>
            <td>0</td>
            <td>0</td>
        </tr>
        <tr>
            <td align="center">Check Install II</td>
            <td>0</td>
            <td>0</td>
        </tr>
        <tr>
            <td align="center">Check Install III</td>
            <td>0</td>
            <td>0</td>
        </tr>*@
                                        <tr>
                                            <td>Business</td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td align="center">Check Install III</td>
                                            <td>@Model.check_Install_3_Day.ordercount</td>
                                            <td>@Model.check_Install_3_Day.MinimumDays</td>
                                        </tr>
                                        <tr>
                                            <td align="center">Check Install II</td>
                                            <td>@Model.check_Install_2_Day.ordercount</td>
                                            <td>@Model.check_Install_2_Day.MinimumDays</td>
                                        </tr>
                                        <tr>
                                            <td align="center">Check Install I</td>
                                            <td>@Model.check_Install_1_Day.ordercount</td>
                                            <td>@Model.check_Install_1_Day.MinimumDays</td>
                                        </tr>
                                        <tr>
                                            <td align="center">Check Install Day</td>
                                            <td>@Model.check_Install_Day.ordercount</td>
                                            <td>@Model.check_Install_Day.MinimumDays</td>
                                        </tr>
                                        <tr>
                                            <td align="center">Post Install Day</td>
                                            <td>@Model.post_Install_Day.ordercount</td>
                                            <td>@Model.post_Install_Day.MinimumDays</td>
                                        </tr>
                                    </table>

                                </fieldset>
                            </div>
                        </div>
                    </div>
                </td>
                <td class="stroke" height="1" width="1"></td>
            </tr>
            <tr>
                <td class="stroke" colspan="3" height="1"></td>
            </tr>
        </table>
    </div>
</body>

smb_om/smb_om/Views/OpsAdmin/ReasonCode.cshtml
@model smb_om.Model.MasterReasonCode
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<body>
    <div id="content-body">
        <div class="application">
            <h1>Reason Code Admin</h1>
            <ul class="nav nav-tabs" style="border-right:0;border-left:0;">
                <li class="active"><a data-toggle="tab" href="#business">Existing Business - SMBC</a></li>

            </ul>
            <div class="tab-pane fade active in" id="business" style="padding:10px;">
                <div id="dataTable-smbc_wrapper" class="dataTables_wrapper no-footer">
                    <div class="dataTables_scroll">

                        <div class="dataTables_scrollHead" style="overflow: hidden; position: relative; border: 0px; width: 100%;">
                            <div class="dataTables_scrollHeadInner" style="box-sizing: content-box; width: 951px; padding-right: 16px;">
                                <table class="display stripe dataTable no-footer" width="100%" role="grid" style="margin-left: 0px; width: 951px;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 281px;">Reason Code</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 281px;">Reason</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 281px;"></th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div><div class="dataTables_scrollBody" style="overflow: auto; height: 400px; width: 100%;">
                            <table class="display stripe dataTable no-footer" id="dataTable-smbc" width="100%" role="grid" aria-describedby="dataTable-smbc_info" style="width: 100%;">
                                <thead>
                                    <tr role="row" style="height: 0px;">
                                        <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 100px; padding-top: 0px; padding-bottom: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 0px;">
                                            <div class="dataTables_sizing" style="height:0;overflow:hidden;">Reason Code</div>
                                        </th>
                                        <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 100px; padding-top: 0px; padding-bottom: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 0px;">
                                            <div class="dataTables_sizing" style="height:0;overflow:hidden;">Reason</div>
                                        </th>
                                        <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 100px; padding-top: 0px; padding-bottom: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 0px;">
                                            <div class="dataTables_sizing" style="height:0;overflow:hidden;"></div>
                                        </th>
                                        <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 50px; padding-top: 0px; padding-bottom: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 0px;">
                                            <div class="dataTables_sizing" style="height:0;overflow:hidden;"></div>
                                        </th>
                                        <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 50px; padding-top: 0px; padding-bottom: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 0px;">
                                            <div class="dataTables_sizing" style="height:0;overflow:hidden;"></div>
                                        </th>
                                        <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 50px; padding-top: 0px; padding-bottom: 0px; border-top-width: 0px; border-bottom-width: 0px; height: 0px;">
                                            <div class="dataTables_sizing" style="height:0;overflow:hidden;"></div>
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @*<tr role="row" class="odd"><td>6</td><td>IT Follow-up</td><td><a class="reasonCodeLinks" href="#" onclick="showReasonCodePopup(6,'dataTable-smbc')">Edit</a></td>
                                        </tr>*@
                                @if (Model != null && Model.reasonCodeResults != null && Model.reasonCodeResults.Count > 0)
                                {
                                    @foreach (var item in Model.reasonCodeResults)
                                    {
                                    <tr role="row" class="odd">
                                        <td>@item.ReasonCode</td>
                                        <td><label style="display:block" id="lbl_@item.Row_ID">@item.ReasonCodeName</label></td>
                                        <td><input type="text" id="txt_@item.Row_ID" value="@item.ReasonCodeName" style="display:none;" /> </td>
                                        @*<td><a class="reasonCodeLinks" href="javascript:Edit(@item.Row_ID)">Edit</a></td>*@
                                        <td align="center">
                                            <input class="button-css" id="btnedit_@item.Row_ID" name="removeButton_4"
                                                   onclick="show(@item.Row_ID)"
                                                   style="display:block"
                                                   type="button"
                                                   value="Edit" />
                                        </td>
                                        <td align="center">
                                            <input class="button-css" id="btnupdate_@item.Row_ID" name="removeButton_4"
                                                   onclick="Edit(@item.Row_ID)"
                                                   style="display: none"
                                                   type="button"
                                                   value="Update" />
                                        </td>
                                        <td align="center">
                                            <input class="button-css" id="btncancel_@item.Row_ID" name="removeButton_4"
                                                   onclick="cancel(@item.Row_ID)"
                                                   style="display: none"
                                                   type="button"
                                                   value="Cancel" />
                                        </td>
                                        @*<td><a class="reasonCodeLinks" href="#" onclick="Edit(@item.Row_ID)">Update</a></td>*@
                                    </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                @*<div class="dataTables_info" id="dataTable-smbc_info" role="status" aria-live="polite">Showing 1 to 43 of 43 entries</div>*@
            </div>
        </div>
    </div>
</div>

    <script type="text/javascript">
            function Edit(RowID) {
                txt = RowID;
             //   var lableid = $("#lbl_" + RowID);
            //    $("#lbl_" + RowID).css('display', 'none');
               // alert(lableid);
               // lableid.style.display = "none";
             //   var txtid = $("#txt_" + RowID);
                var inputid = $("#txt_" + RowID).val();

                $.getJSON('@Url.Content("~/")' + "OpsAdmin/ReasonCodeUpdate?Rowid=" + txt + "&reasoncode=" + inputid, function (orderupdate) {
                    if (orderupdate > 0) {
                        alert("Reason code : Updated Successfully");
                        window.location.reload();
                        txtid.style.display = "none";
                        lableid.style.display = "block";

                        $("#lbl_" + RowID).css('display', 'block');
                        $("#txt_" + RowID).css('display', 'none');
                        $("#btnedit_" + RowID).css('display', 'block');
                        $("#btnupdate_" + RowID).css('display', 'none');
                        $("#btncancel_" + RowID).css('display', 'none');
                        window.location.reload();
                    }
                    else {
                        alert("Reason code : Not able to  Update currently");
                    }
                });
            }

     function show(RowID) {
         var txt;
         txt = RowID;
         //   var lableid = $("#lbl_" + RowID);
         $("#lbl_" + RowID).css('display', 'none');
         $("#txt_" + RowID).css('display', 'block');
         $("#btnedit_" + RowID).css('display', 'none');
         $("#btnupdate_" + RowID).css('display', 'block');
         $("#btncancel_" + RowID).css('display', 'block');
         
         // alert(lableid);
         // lableid.style.display = "none";
        }
        function cancel(RowID) {
            var txt;
            txt = RowID;
            //   var lableid = $("#lbl_" + RowID);
            $("#lbl_" + RowID).css('display', 'block');
            $("#txt_" + RowID).css('display', 'none');
            $("#btnedit_" + RowID).css('display', 'block');
            $("#btnupdate_" + RowID).css('display', 'none');
            $("#btncancel_" + RowID).css('display', 'none');
            // alert(lableid);
            // lableid.style.display = "none";
        }
    </script>

</body>